trigger:
- master

pr: none

jobs:  
- job: Build
  displayName: Build

  steps:
  - task: Npm@1
    inputs:
      command: 'install'
      
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@0
    displayName: 'Publish pipeline artifacts'
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip